name: Backend code check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go environment
        uses: actions/setup-go@v5
        with:
          go-version-file: 'backend/go.mod'
          cache: true

      - name: Check formatting
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "The following files are not formatted:"
            gofmt -l .
            exit 1
          fi

      - name: Go Vet
        run: go vet ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          working-directory: backend

      - name: Run Tests
        run: go test -v -race -coverprofile=coverate.out ./...
